before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/security-checker
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/security-checker
  - cp -r ./. /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/security-checker
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/security-checker
  - source ~/.ossenv

variables:
  PROJECT: "security-checker"

stages:
  - deploy

#build-dev:
#  stage: deploy
#  only:
#    - dev
#  script:
#    # only check building, not publish
#    - make ci_notify
#    - make testing
#    - make test_notify
#  tags:
#    - cloudcare-ft

build-testing:
  stage: deploy
  only:
    - dev
  script:
    # building && publish testing
    #- make ci_notify
    - make testing
    - make pub_testing
    #- make pub_testing_img
    #- make test_notify
  tags:
    - cloudcare-ft

# build-release:
#   stage: deploy
#   only:
#     - master
#   script:
#     - make ci_notify
#     - make release
#     - make pub_release
#     - make pub_release_img
#     - make release_notify
#   tags:
#     - cloudcare-ft
