before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/sec-checker
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/sec-checker
  - cp -r ./. /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/sec-checker
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/sec-checker
  - source ~/.ossenv

variables:
  PROJECT: "security-checker"

stages:
  - deploy

build-testing:
  stage: deploy
  only:
    - testing
  script:
    # building && publish testing
    - make testing
    - make pub_testing
  tags:
    - cloudcare-ft

build-release:
  stage: deploy
  only:
    - master
  script:
    - make release
    - make pub_release
  tags:
    - cloudcare-ft
